### ISSUE TITLE
Support for non-spring animations?

### ISSUE THREAD

**Issue by james01** [jtrivedi/Wave#29]
This is an awesome library. Thanks for building it.

I was wondering - Do you have any plans for supporting non-spring animations (i.e. ease-in-out or linear)? Or are they already there and I missed it?

Thanks.

**Comment by jtrivedi** [comment]
Hi, thanks for reaching out!

I’m not planning to support non-spring animations. It’s difficult to “retarget” timing-curve based animations, which is the value of Wave.
