### ISSUE TITLE
macOS version

### ISSUE THREAD

**Issue by erikng** [jtrivedi/Wave#6]
I don't know how feasible this would be as you use a lot of UIKit, but what about some level of AppKit support? I don't mean Catalyst support as I imagine that may work out of the box.

Maybe next week Apple will announce something to better bridge the gap.

If this is something you don't ever want to support, feel free to close this. Awesome work!

**Comment by flocked** [comment]
I managed to fully port Wave to MacOS & NSView. It works great. :) When I find time I will clean up my code and will upload it.

**Comment by erikng** [comment]
Nice!

**Comment by flocked** [comment]
Here it is. It just misses a sample project
https://github.com/flocked/Wave/tree/main

It's my first time ever trying to combine iOS/macOS into one shared code. So there might be better code. 
It surprisingly didn't require a ton of changes.

**Comment by jtrivedi** [comment]
Hey @erikng and @flocked, I'll be landing macOS/AppKit support in Wave soon with this PR.

Feel free to reach out with any questions or issues!

https://github.com/jtrivedi/Wave/pull/25

**Comment by jtrivedi** [comment]
Resolved with #25
